{% set name = "httpdbg" %}
{% set version = "0.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/httpdbg-{{ version }}.tar.gz
  sha256: b500b67c34d2dc8498b716bb44fa732c59b434eb091f5784bcca47d12378ceb1

build:
  entry_points:
    - pyhttpdbg = httpdbg.__main__:pyhttpdbg_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - httpdbg
  commands:
    - pip check
    - pyhttpdbg --help
  requires:
    - pip

about:
  home: https://github.com/cle-b/httpdbg/
  summary: A tool for Python developers to easily debug the HTTP(S) client requests in a Python program.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
