{% set name = "httpdbg" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/httpdbg-{{ version }}.tar.gz
  sha256: 2d3cce368295d148d7f54b07fcc811d6f9b91efff124a8eb1460fe941e198759

build:
  entry_points:
    - pyhttpdbg = httpdbg.__main__:pyhttpdbg_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - httpdbg
  commands:
    - pip check
    - pyhttpdbg --help
  requires:
    - pip

about:
  home: https://github.com/cle-b/httpdbg/
  summary: A tool for Python developers to easily debug the HTTP(S) client requests in a Python program.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
