schema_version: 1

context:
  name: httpdbg
  version: "2.0.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/httpdbg-${{ version }}.tar.gz
  sha256: ac69eff94f9469df1696d5094b5cdeaeaecece5850adacd4314cf8ee4d7a87af

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pyhttpdbg = httpdbg.__main__:pyhttpdbg_entry_point

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - wheel
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - httpdbg
      pip_check: true
      python_version: ${{ python_min }}.*
  - script:
      - pyhttpdbg --help

about:
  summary: A tool for Python developers to easily debug the HTTP(S) client requests in a Python program.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/cle-b/httpdbg/

extra:
  recipe-maintainers:
    - thewchan
